import { Niche } from "./platforms-data";

export interface Opportunity {
  id: string;
  platformId: string;
  platformName: string;
  brand: string;
  title: string;
  description: string;
  payMin: number;
  payMax: number;
  payDisplay: string;
  niches: Niche[];
  contentType: "video" | "photo" | "both";
  deliverables: string[];
  deadline?: string;
  postedAt: string;
  applyUrl: string;
  isNew: boolean;
  spotsLeft?: number;
  country?: string;
  sourceType?: "public" | "logged-in" | "email" | "community";
  requiresPosting?: boolean;
  giftedOnly?: boolean;
  followerRequirement?: string;
}

// Seed opportunities — in production these get scraped / submitted by users
export const opportunities: Opportunity[] = [
  {
    id: "opp-sideshift-1",
    platformId: "sideshift",
    platformName: "SideShift",
    brand: "SwipeWell",
    title: "Dating app testimonial, TikTok style",
    description:
      "Create a fast-cut testimonial about trying a new dating app feature. Hook-heavy UGC style, selfie format, casual voiceover accepted.",
    payMin: 75,
    payMax: 150,
    payDisplay: "$75 + CPM",
    niches: ["tech", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 15-sec video", "Posted TikTok/Reel"],
    deadline: "2026-05-29",
    postedAt: "2026-05-20",
    applyUrl: "https://sideshift.app/creators",
    isNew: true,
    spotsLeft: 6,
    country: "US",
    sourceType: "logged-in",
    requiresPosting: true,
    giftedOnly: false,
    followerRequirement: "No minimum listed",
  },
  {
    id: "opp-sideshift-2",
    platformId: "sideshift",
    platformName: "SideShift",
    brand: "StudySprint",
    title: "Student productivity app UGC",
    description:
      "Film a short day-in-the-life clip showing how you use a focus timer app between classes, work, or content shoots.",
    payMin: 50,
    payMax: 120,
    payDisplay: "$50–$120",
    niches: ["tech", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 20-sec video", "Raw footage"],
    deadline: "2026-06-02",
    postedAt: "2026-05-20",
    applyUrl: "https://sideshift.app/creators",
    isNew: true,
    spotsLeft: 11,
    country: "US",
    sourceType: "logged-in",
    requiresPosting: false,
    giftedOnly: false,
    followerRequirement: "No minimum listed",
  },
  {
    id: "opp-1",
    platformId: "billo",
    platformName: "Billo",
    brand: "NovaSkin",
    title: "30-second skincare routine video",
    description:
      "Show your morning skincare routine featuring our NovaSkin Vitamin C serum. Natural, unscripted feel. Film in good lighting at home.",
    payMin: 80,
    payMax: 80,
    payDisplay: "$80",
    niches: ["beauty", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 30-sec video", "Raw footage"],
    deadline: "2026-06-01",
    postedAt: "2026-05-18",
    applyUrl: "https://billo.app",
    isNew: true,
    spotsLeft: 8,
  },
  {
    id: "opp-2",
    platformId: "insense",
    platformName: "Insense",
    brand: "GainX Supplements",
    title: "Pre-workout unboxing + first impression",
    description:
      "Unbox our new pre-workout, taste test on camera, give your honest first impression. Gym or home setting preferred.",
    payMin: 150,
    payMax: 200,
    payDisplay: "$150–$200",
    niches: ["fitness", "health"],
    contentType: "video",
    deliverables: ["1x 45–60 sec video", "3 story clips"],
    deadline: "2026-05-28",
    postedAt: "2026-05-17",
    applyUrl: "https://insense.pro",
    isNew: true,
    spotsLeft: 5,
  },
  {
    id: "opp-3",
    platformId: "joinbrands",
    platformName: "JoinBrands",
    brand: "PawLife Co.",
    title: "Dog treat review video",
    description:
      "Film your dog trying our new grain-free treats. Capture reaction, your honest review, and a happy pup moment.",
    payMin: 65,
    payMax: 90,
    payDisplay: "$65–$90",
    niches: ["pets", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 30-sec video"],
    postedAt: "2026-05-19",
    applyUrl: "https://joinbrands.com",
    isNew: true,
    spotsLeft: 12,
  },
  {
    id: "opp-4",
    platformId: "cohley",
    platformName: "Cohley",
    brand: "HomeNest",
    title: "Kitchen appliance lifestyle photos",
    description:
      "5 lifestyle photos of our new air fryer in your kitchen. Natural light, styled but lived-in feel. No white backgrounds.",
    payMin: 300,
    payMax: 300,
    payDisplay: "$300",
    niches: ["home", "food", "lifestyle"],
    contentType: "photo",
    deliverables: ["5x edited lifestyle photos", "RAW files"],
    deadline: "2026-06-05",
    postedAt: "2026-05-16",
    applyUrl: "https://www.cohley.com",
    isNew: false,
    spotsLeft: 3,
  },
  {
    id: "opp-5",
    platformId: "collabstr",
    platformName: "Collabstr",
    brand: "FitFlow Apparel",
    title: "Workout outfit try-on video",
    description:
      "Try on 3 pieces from our new summer collection. Show fit, fabric, and movement. Authentic commentary welcome.",
    payMin: 120,
    payMax: 175,
    payDisplay: "$120–$175",
    niches: ["fitness", "fashion", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 45-sec TikTok-style video"],
    postedAt: "2026-05-19",
    applyUrl: "https://collabstr.com",
    isNew: true,
    spotsLeft: 7,
  },
  {
    id: "opp-6",
    platformId: "insense",
    platformName: "Insense",
    brand: "MealKit Direct",
    title: "Cooking with meal kit — reel",
    description:
      "Receive our weekly meal kit. Cook one meal on camera, show the process, taste reaction, final dish. Must look appetizing.",
    payMin: 180,
    payMax: 220,
    payDisplay: "$180–$220",
    niches: ["food", "lifestyle", "health"],
    contentType: "video",
    deliverables: ["1x 60-sec reel", "2 photos of finished dish"],
    deadline: "2026-05-30",
    postedAt: "2026-05-15",
    applyUrl: "https://insense.pro",
    isNew: false,
    spotsLeft: 4,
  },
  {
    id: "opp-7",
    platformId: "popular-pays",
    platformName: "Popular Pays",
    brand: "Lumi Baby",
    title: "Baby product demo — parent POV",
    description:
      "Demo our smart baby monitor in a natural home setting. Show setup, app features, and your honest parent take on it.",
    payMin: 200,
    payMax: 250,
    payDisplay: "$200–$250",
    niches: ["parenting", "tech", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 60-sec video", "Instagram story set (3)"],
    deadline: "2026-06-10",
    postedAt: "2026-05-18",
    applyUrl: "https://popularpays.com",
    isNew: true,
    spotsLeft: 6,
  },
  {
    id: "opp-8",
    platformId: "billo",
    platformName: "Billo",
    brand: "DeskSetup Pro",
    title: "Home office setup reveal",
    description:
      "Feature our monitor arm / cable management kit in your home office. Before and after format. Tech or productivity angle.",
    payMin: 95,
    payMax: 95,
    payDisplay: "$95",
    niches: ["tech", "lifestyle", "home"],
    contentType: "video",
    deliverables: ["1x 45-sec video"],
    postedAt: "2026-05-17",
    applyUrl: "https://billo.app",
    isNew: false,
    spotsLeft: 10,
  },
  {
    id: "opp-9",
    platformId: "cohley",
    platformName: "Cohley",
    brand: "Aura Beauty",
    title: "Get-ready-with-me makeup video",
    description:
      "Full GRWM featuring our new foundation + setting spray. Film in natural morning light. Authentic, not overly produced.",
    payMin: 250,
    payMax: 350,
    payDisplay: "$250–$350",
    niches: ["beauty", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 60–90 sec video", "3 behind-the-scenes photos"],
    deadline: "2026-06-03",
    postedAt: "2026-05-14",
    applyUrl: "https://www.cohley.com",
    isNew: false,
    spotsLeft: 2,
  },
  {
    id: "opp-10",
    platformId: "joinbrands",
    platformName: "JoinBrands",
    brand: "TrailMix Snacks",
    title: "Healthy snack unboxing + taste test",
    description:
      "Unbox our variety snack box and try 3+ items on camera. Honest reactions, no script needed. Outdoor or kitchen setting.",
    payMin: 55,
    payMax: 75,
    payDisplay: "$55–$75",
    niches: ["food", "fitness", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 30-sec video"],
    postedAt: "2026-05-19",
    applyUrl: "https://joinbrands.com",
    isNew: true,
    spotsLeft: 15,
  },
  {
    id: "opp-11",
    platformId: "tribe",
    platformName: "TRIBE",
    brand: "Wander Luggage",
    title: "Travel lifestyle photo set",
    description:
      "3 lifestyle photos featuring our carry-on at an airport, hotel, or travel destination. Aspirational but authentic.",
    payMin: 150,
    payMax: 250,
    payDisplay: "$150–$250",
    niches: ["travel", "lifestyle", "fashion"],
    contentType: "photo",
    deliverables: ["3x edited photos"],
    postedAt: "2026-05-16",
    applyUrl: "https://www.tribegroup.co",
    isNew: false,
    spotsLeft: 5,
  },
  {
    id: "opp-12",
    platformId: "hashtagpaid",
    platformName: "Hashtagpaid",
    brand: "ZenSpace Wellness",
    title: "Morning wellness routine reel",
    description:
      "Feature our adaptogen supplement in your morning routine. Calm, aesthetic, wellness-forward. Voice over or text overlay.",
    payMin: 130,
    payMax: 180,
    payDisplay: "$130–$180",
    niches: ["health", "wellness", "lifestyle"],
    contentType: "video",
    deliverables: ["1x 30-sec reel"],
    deadline: "2026-06-07",
    postedAt: "2026-05-17",
    applyUrl: "https://hashtagpaid.com",
    isNew: true,
    spotsLeft: 9,
  },
];
