export type Niche =
  | "beauty"
  | "fitness"
  | "food"
  | "tech"
  | "pets"
  | "parenting"
  | "fashion"
  | "home"
  | "travel"
  | "finance"
  | "gaming"
  | "lifestyle"
  | "health"
  | "wellness"
  | "automotive";

export type ContentType = "video" | "photo" | "both";
export type DifficultyLevel = "easy" | "medium" | "hard";

export interface Platform {
  id: string;
  name: string;
  url: string;
  signupUrl: string;
  logo: string;
  description: string;
  avgPay: string;
  payRange: string;
  niches: Niche[];
  contentTypes: ContentType[];
  approvalDifficulty: DifficultyLevel;
  followerRequired: boolean;
  minFollowers?: number;
  paymentMethod: string;
  paymentFrequency: string;
  notes: string;
  tags: string[];
  rating: number;
}

export const platforms: Platform[] = [
  {
    id: "sideshift",
    name: "SideShift",
    url: "https://sideshift.app",
    signupUrl: "https://sideshift.app/creators",
    logo: "SS",
    description:
      "Mobile-first UGC marketplace with one-tap applications, creator jobs, and performance-based opportunities.",
    avgPay: "$30–$150+",
    payRange: "$30–$500+",
    niches: ["tech", "beauty", "fitness", "lifestyle", "fashion", "food"],
    contentTypes: ["video"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "Bank transfer",
    paymentFrequency: "Per gig / performance",
    notes:
      "High-volume feed. Check posting requirements carefully because some jobs require social posting or performance payouts.",
    tags: ["mobile-app", "one-tap-apply", "performance-payouts"],
    rating: 4.0,
  },
  {
    id: "billo",
    name: "Billo",
    url: "https://billo.app",
    signupUrl: "https://billo.app/for-creators/",
    logo: "B",
    description:
      "One of the largest UGC video platforms. Brands post tasks, creators apply. Strong mobile app.",
    avgPay: "$50–$150",
    payRange: "$30–$300",
    niches: ["beauty", "fitness", "food", "tech", "pets", "home", "lifestyle"],
    contentTypes: ["video"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Great starting point. New creators start at $30/video.",
    tags: ["beginner-friendly", "high-volume", "video-only"],
    rating: 4.5,
  },
  {
    id: "insense",
    name: "Insense",
    url: "https://insense.pro",
    signupUrl: "https://insense.pro/creators",
    logo: "I",
    description:
      "Premium UGC + influencer platform. Brands often pay more here. Good for creators with engaged audiences.",
    avgPay: "$100–$300",
    payRange: "$50–$500",
    niches: ["beauty", "fashion", "fitness", "lifestyle", "food", "travel"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "Bank transfer / PayPal",
    paymentFrequency: "Per gig",
    notes: "Higher pay but more selective. Quality profile matters.",
    tags: ["higher-pay", "selective", "photos-and-video"],
    rating: 4.3,
  },
  {
    id: "joinbrands",
    name: "JoinBrands",
    url: "https://joinbrands.com",
    signupUrl: "https://joinbrands.com/creators",
    logo: "J",
    description:
      "Growing platform with lots of Amazon brand deals. Good for product review style content.",
    avgPay: "$75–$200",
    payRange: "$40–$400",
    niches: ["tech", "home", "beauty", "fitness", "pets", "parenting"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Lots of Amazon sellers here. Great for unboxing/review content.",
    tags: ["amazon-brands", "review-content", "beginner-friendly"],
    rating: 4.2,
  },
  {
    id: "cohley",
    name: "Cohley",
    url: "https://www.cohley.com",
    signupUrl: "https://www.cohley.com/creators",
    logo: "C",
    description:
      "Professional UGC platform used by major brands. Higher standards, higher rewards.",
    avgPay: "$150–$400",
    payRange: "$100–$800",
    niches: ["beauty", "food", "lifestyle", "fitness", "fashion", "home"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "hard",
    followerRequired: false,
    paymentMethod: "Check / Direct deposit",
    paymentFrequency: "Per gig",
    notes:
      "Major CPG brands use this. More competitive but pays significantly more.",
    tags: ["enterprise-brands", "high-pay", "professional"],
    rating: 4.6,
  },
  {
    id: "collabstr",
    name: "Collabstr",
    url: "https://collabstr.com",
    signupUrl: "https://collabstr.com/get-started",
    logo: "Co",
    description:
      "Marketplace where you set your own rates. Brands come to you. Great for building a portfolio.",
    avgPay: "You set it",
    payRange: "$50–$500+",
    niches: [
      "beauty",
      "fitness",
      "lifestyle",
      "food",
      "tech",
      "fashion",
      "travel",
    ],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "Stripe",
    paymentFrequency: "Per gig",
    notes:
      "You create a profile with your packages. Brands find you. No need to apply.",
    tags: ["inbound", "set-your-rates", "portfolio"],
    rating: 4.1,
  },
  {
    id: "twirl",
    name: "Twirl",
    url: "https://www.usetwirl.com",
    signupUrl: "https://www.usetwirl.com/for-creators",
    logo: "T",
    description:
      "Video-first UGC platform focused on short-form content. Strong TikTok-style jobs.",
    avgPay: "$75–$200",
    payRange: "$50–$300",
    niches: ["beauty", "lifestyle", "food", "fitness", "fashion"],
    contentTypes: ["video"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Great for creators comfortable with TikTok-style content.",
    tags: ["video-first", "short-form", "tiktok-style"],
    rating: 3.9,
  },
  {
    id: "trend",
    name: "Trend",
    url: "https://www.trend.io",
    signupUrl: "https://www.trend.io/creators",
    logo: "Tr",
    description:
      "Curated UGC marketplace. Selective approval but strong brand relationships.",
    avgPay: "$100–$300",
    payRange: "$75–$500",
    niches: ["lifestyle", "beauty", "fitness", "food", "fashion"],
    contentTypes: ["photo", "video", "both"],
    approvalDifficulty: "hard",
    followerRequired: true,
    minFollowers: 1000,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Curated platform — take time with your application.",
    tags: ["curated", "selective", "quality-brands"],
    rating: 4.4,
  },
  {
    id: "creator-co",
    name: "Creator.co",
    url: "https://creator.co",
    signupUrl: "https://creator.co",
    logo: "Cc",
    description:
      "Platform that blends UGC and influencer marketing. Good for creators with any following size.",
    avgPay: "$80–$250",
    payRange: "$50–$600",
    niches: ["beauty", "fashion", "lifestyle", "fitness", "travel", "food"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Active community. Good volume of opportunities.",
    tags: ["ugc-and-influencer", "community", "active"],
    rating: 4.0,
  },
  {
    id: "popular-pays",
    name: "Popular Pays",
    url: "https://popularpays.com",
    signupUrl: "https://popularpays.com/creator",
    logo: "PP",
    description:
      "Chicago-based platform with strong CPG and DTC brand presence. Creative jobs.",
    avgPay: "$100–$350",
    payRange: "$75–$700",
    niches: ["food", "beauty", "lifestyle", "fitness", "fashion", "home"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "Direct deposit",
    paymentFrequency: "Per gig",
    notes: "Strong brand roster. Responsive platform team.",
    tags: ["cpg-brands", "dtc", "creative"],
    rating: 4.3,
  },
  {
    id: "hashtagpaid",
    name: "Hashtagpaid",
    url: "https://hashtagpaid.com",
    signupUrl: "https://hashtagpaid.com/creators",
    logo: "H#",
    description:
      "Canadian platform with North American brand reach. Good for lifestyle and wellness creators.",
    avgPay: "$100–$300",
    payRange: "$75–$500",
    niches: ["lifestyle", "wellness", "beauty", "food", "fitness", "health"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Strong wellness and CPG brands. Less competitive than US-only platforms.",
    tags: ["north-america", "wellness", "lifestyle"],
    rating: 4.1,
  },
  {
    id: "peersway",
    name: "Peersway",
    url: "https://peersway.com",
    signupUrl: "https://peersway.com/influencers",
    logo: "Ps",
    description:
      "Product-gifting focused platform. Receive free products in exchange for authentic content.",
    avgPay: "Free product",
    payRange: "Product + $0–$100",
    niches: ["beauty", "lifestyle", "food", "fitness", "home", "pets"],
    contentTypes: ["photo", "video", "both"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "Product gifting",
    paymentFrequency: "Per gig",
    notes:
      "Great for building portfolio with real products. Some paid gigs too.",
    tags: ["gifted", "portfolio-building", "beginner"],
    rating: 3.8,
  },
  {
    id: "shopltk",
    name: "ShopLTK",
    url: "https://company.shopltk.com",
    signupUrl: "https://company.shopltk.com/en/creator",
    logo: "LK",
    description:
      "LikeToKnowIt / LTK — affiliate-first platform with brand collaboration opportunities.",
    avgPay: "Commission + flat fee",
    payRange: "$50–$500+",
    niches: ["fashion", "beauty", "home", "lifestyle", "fitness"],
    contentTypes: ["photo", "video", "both"],
    approvalDifficulty: "medium",
    followerRequired: true,
    minFollowers: 5000,
    paymentMethod: "Direct deposit",
    paymentFrequency: "Monthly commissions",
    notes: "Best for fashion/style creators. Affiliate + brand deals combined.",
    tags: ["affiliate", "fashion", "style", "home"],
    rating: 4.2,
  },
  {
    id: "beeroll",
    name: "Beeroll",
    url: "https://www.beeroll.io",
    signupUrl: "https://www.beeroll.io",
    logo: "Br",
    description:
      "Newer platform focused on video UGC. Lower competition due to smaller size.",
    avgPay: "$60–$180",
    payRange: "$40–$250",
    niches: ["lifestyle", "beauty", "food", "fitness", "tech"],
    contentTypes: ["video"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Newer platform = less competition. Good for getting early wins.",
    tags: ["newer", "less-competition", "video"],
    rating: 3.7,
  },
  {
    id: "brandsmeetcreators",
    name: "Brands Meet Creators",
    url: "https://brandsmeetcreators.com",
    signupUrl: "https://brandsmeetcreators.com",
    logo: "BM",
    description:
      "UK-based platform with international reach. Good mix of content types.",
    avgPay: "$75–$220",
    payRange: "$50–$400",
    niches: ["beauty", "lifestyle", "fashion", "food", "fitness"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "UK origin, global reach. Good for international creators.",
    tags: ["uk-based", "international", "growing"],
    rating: 3.9,
  },
  {
    id: "obviously",
    name: "Obviously",
    url: "https://www.obvious.ly",
    signupUrl: "https://www.obvious.ly/influencers",
    logo: "Ob",
    description:
      "Premium influencer + UGC agency-style platform. Higher pay for approved creators.",
    avgPay: "$150–$500",
    payRange: "$100–$1000+",
    niches: ["fashion", "beauty", "lifestyle", "parenting", "food", "travel"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "hard",
    followerRequired: true,
    minFollowers: 2000,
    paymentMethod: "Check / wire",
    paymentFrequency: "Per campaign",
    notes: "Agency-quality platform. Selective but top-tier pay.",
    tags: ["premium", "agency", "high-pay", "selective"],
    rating: 4.5,
  },
  {
    id: "tribe",
    name: "TRIBE",
    url: "https://www.tribegroup.co",
    signupUrl: "https://www.tribegroup.co/influencers",
    logo: "Tb",
    description:
      "Creator-pitches-to-brand model. You create the content first, brand buys it.",
    avgPay: "$100–$300",
    payRange: "$75–$500",
    niches: ["lifestyle", "food", "beauty", "fitness", "travel", "parenting"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "easy",
    followerRequired: true,
    minFollowers: 3000,
    paymentMethod: "PayPal",
    paymentFrequency: "Per content piece purchased",
    notes:
      "Unique model — you pitch your content to brands. Great creative freedom.",
    tags: ["creator-pitches", "creative-freedom", "photo-heavy"],
    rating: 4.0,
  },
  {
    id: "social-native",
    name: "Social Native",
    url: "https://www.socialnative.com",
    signupUrl: "https://www.socialnative.com",
    logo: "SN",
    description:
      "Enterprise UGC platform. Works with major retailers and Fortune 500 brands.",
    avgPay: "$100–$400",
    payRange: "$75–$600",
    niches: ["beauty", "fashion", "food", "lifestyle", "fitness", "home"],
    contentTypes: ["photo", "video", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Big brand clients. Professional quality expected.",
    tags: ["enterprise", "major-brands", "retail"],
    rating: 4.2,
  },
  {
    id: "skeepers",
    name: "Skeepers",
    url: "https://skeepers.io",
    signupUrl: "https://skeepers.io/en",
    logo: "Sk",
    description:
      "European-rooted platform now global. Strong in beauty, retail, and lifestyle.",
    avgPay: "$80–$250",
    payRange: "$50–$400",
    niches: ["beauty", "fashion", "lifestyle", "food", "home"],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "medium",
    followerRequired: false,
    paymentMethod: "Bank transfer",
    paymentFrequency: "Per gig",
    notes: "European roots, growing in US. Less competition from US creators.",
    tags: ["european", "growing", "retail"],
    rating: 4.0,
  },
  {
    id: "showcase",
    name: "Showcase",
    url: "https://www.showca.se",
    signupUrl: "https://www.showca.se",
    logo: "Sw",
    description:
      "Portfolio + marketplace hybrid. Build your creator page and get discovered.",
    avgPay: "Varies",
    payRange: "$50–$500",
    niches: [
      "beauty",
      "lifestyle",
      "fitness",
      "fashion",
      "food",
      "tech",
      "travel",
    ],
    contentTypes: ["video", "photo", "both"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "Various",
    paymentFrequency: "Per gig",
    notes: "Good for portfolio visibility. Inbound brand inquiries.",
    tags: ["portfolio", "inbound", "discovery"],
    rating: 3.8,
  },
  {
    id: "taggbox",
    name: "Taggbox",
    url: "https://taggbox.com",
    signupUrl: "https://taggbox.com",
    logo: "Tg",
    description:
      "UGC aggregation platform with creator opportunities. Brands use it for social proof.",
    avgPay: "$50–$200",
    payRange: "$30–$300",
    niches: ["lifestyle", "beauty", "food", "fitness", "tech"],
    contentTypes: ["photo", "video", "both"],
    approvalDifficulty: "easy",
    followerRequired: false,
    paymentMethod: "PayPal",
    paymentFrequency: "Per gig",
    notes: "Unique social proof angle. Good supplementary income platform.",
    tags: ["social-proof", "aggregation", "supplementary"],
    rating: 3.6,
  },
];

export const niches: { value: Niche; label: string; emoji: string }[] = [
  { value: "beauty", label: "Beauty & Skincare", emoji: "💄" },
  { value: "fitness", label: "Fitness & Wellness", emoji: "💪" },
  { value: "food", label: "Food & Beverage", emoji: "🍕" },
  { value: "tech", label: "Tech & Gadgets", emoji: "📱" },
  { value: "pets", label: "Pets & Animals", emoji: "🐾" },
  { value: "parenting", label: "Parenting & Family", emoji: "👨‍👩‍👧" },
  { value: "fashion", label: "Fashion & Style", emoji: "👗" },
  { value: "home", label: "Home & Living", emoji: "🏠" },
  { value: "travel", label: "Travel & Adventure", emoji: "✈️" },
  { value: "finance", label: "Finance & Money", emoji: "💰" },
  { value: "gaming", label: "Gaming", emoji: "🎮" },
  { value: "lifestyle", label: "Lifestyle", emoji: "✨" },
  { value: "health", label: "Health", emoji: "🌿" },
  { value: "wellness", label: "Wellness", emoji: "🧘" },
  { value: "automotive", label: "Automotive", emoji: "🚗" },
];
